// projects/svelte/src/App.svelte
<script lang="ts">
  // styles
  import './styles/index.sass'

  // assets
  import Logo from './assets/svelte.png'

  // components
  import AddTodo from './components/AddTodo.svelte'
  import TodoList from './components/TodoList.svelte'
</script>

<div id="app-container">
  <header>
    <h1>
      <a href="/">
        <img src={Logo} alt="Svelte logo" class="logo" />
        Learn Svelte: ToDo</a
      >
    </h1>
  </header>

  <main>
    <article>
      <AddTodo />
      <TodoList />
    </article>
  </main>

  <footer>
    <p>
      A simple todo app built with Svelte and Vite. <a href="/"
        >Back to home →</a
      >
    </p>
    <p>
      Copyright &copy; {new Date().getFullYear()}{' '}
      <a
        href="https://github.com/Dragon-Fish/learn-frontend"
        target="_blank"
        rel="noopener noreferrer"
      >
        Dragon-Fish
      </a>
    </p>
  </footer>
</div>

<style lang="sass">
#app-container
  display: flex
  flex-direction: column
  min-height: 100vh

header, main, footer
  padding: 0 5%

header
  h1
    .logo
      height: 1em
      vertical-align: middle
      margin: 0 0.5em 0 0
    a
      color: inherit
      text-decoration: none

main
  flex: 1
  margin-bottom: 4rem

footer
  background-color: #eee
</style>

// projects/react/src/App.tsx
import { connect } from 'react-redux'
import AddTodo from './components/AddTodo'
import TodoList from './components/TodoList'
import { Todo } from './types/Todo'
import Logo from './logo.svg'

function App({ todos = [] }: { todos: Todo[] }) {
  return (
    <div
      id="app"
      style={{
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
      }}
    >
      <header
        style={{
          padding: '0 5%',
        }}
      >
        <h1>
          <a
            href="/"
            style={{
              color: 'inherit',
              textDecoration: 'none',
            }}
          >
            <img
              src={Logo}
              alt="logo"
              style={{
                height: '1em',
                verticalAlign: 'middle',
              }}
            />
            Learn React: ToDo
          </a>
        </h1>
      </header>
      <main
        style={{
          padding: '0 5% 4rem 5%',
          flex: 1,
        }}
      >
        <article>
          <AddTodo></AddTodo>
          <TodoList></TodoList>
        </article>
      </main>
      <footer
        style={{
          padding: '0 5%',
          backgroundColor: '#eee',
        }}
      >
        <p>
          A simple todo app built with React.js, Redux and Vite.{' '}
          <a href="/"> Back to home →</a>
        </p>
        <p>
          &copy; Copyright (c) {new Date().getFullYear()}{' '}
          <a
            href="https://github.com/Dragon-Fish/learn-frontend"
            target="_blank"
            rel="noopener noreferrer"
          >
            Dragon-Fish
          </a>
        </p>
      </footer>
    </div>
  )
}

export default connect((state: Todo[]) => ({
  todos: state,
}))(App)
