// projects/vue3/src/components/TodoList.vue
<template lang="pug">
.todo-list-container
  .todo-filter
    ul.tabs
      li(:class="{ 'is-active': tab === 'all' }")
        a(@click.prevent="tab = 'all'") All
      li(:class="{ 'is-active': tab === 'active' }")
        a(@click.prevent="tab = 'active'") Active
      li(:class="{ 'is-active': tab === 'completed' }")
        a(@click.prevent="tab = 'completed'") Completed
  .todo-main
    h2 {{ tab.charAt(0).toUpperCase() + tab.slice(1) }} todos
    .todo-empty(v-if="!validTodos.length")
      em Oops, no {{ tab === 'all' ? '' : tab }} todo. Add one!
    ul.todo-list
      todo-card(v-for="(todo, index) in validTodos" :key="index" :todo="todo")
  .todo-extra
    a.clear-completed(@click.prevent="clearCompletedTodos" v-if="!!todoList.find(i=>!!i.completedAt)")
      icon
        broom
      | Clear completed todos
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import TodoCard from './TodoCard.vue'
import { Broom } from '@vicons/fa'
import { todoList, clearCompletedTodos } from '../utils/globalState'

const tab = ref<'all' | 'active' | 'completed'>('all')

const validTodos = computed(() => {
  return [
    ...(() => {
      switch (tab.value) {
        case 'active':
          return todoList.value.filter((todo) => !todo.completedAt)
        case 'completed':
          return todoList.value.filter((todo) => !!todo.completedAt)
        default:
          return todoList.value
      }
    })(),
  ].sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  )
})
</script>

<style scoped lang="sass">
.todo-list-container
  .todo-list
    padding: 0
    display: flex
    flex-direction: row
    flex-wrap: wrap
    gap: 1rem
  .tabs
    list-style: none
    padding: 0
    display: flex
    gap: 1rem
    li
      a
        cursor: pointer
        color: #888
      &.is-active
        a
          color: #000
          text-decoration: underline
  .clear-completed
    color: #888
    cursor: pointer
</style>

// projects/react/src/components/TodoList.tsx
import { useState } from 'react'
import { connect } from 'react-redux'
import { globalStore } from '../main'
import { Todo } from '../types/Todo'
import TodoCard from './TodoCard'

const TodoList = () => {
  let [todos, setTodos] = useState<Todo[]>(globalStore.getState())
  let [tab, setTab] = useState<'all' | 'active' | 'completed'>('all')

  const renderTodo = (tab = 'all') => {
    let list = globalStore.getState()
    switch (tab) {
      case 'active':
        list = list.filter((item) => !item.completedAt)
        break
      case 'completed':
        list = list.filter((item) => !!item.completedAt)
        break
      default:
        list = list
    }
    setTodos(
      list.sort((a, b) => {
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
      })
    )
  }

  globalStore.subscribe(() => renderTodo(tab))

  return (
    <div className="todo-list-container">
      <div className="filter-container">
        <ul
          style={{
            display: 'flex',
            gap: '1rem',
            listStyle: 'none',
            padding: '0',
          }}
        >
          <li>
            <a
              href="javascript:;"
              onClick={(e) => {
                e.preventDefault()
                setTab('all')
                renderTodo('all')
              }}
              style={{
                color: tab === 'all' ? '#000' : '#aaa',
              }}
            >
              All
            </a>
          </li>
          <li>
            <a
              href="javascript:;"
              onClick={(e) => {
                e.preventDefault()
                setTab('active')
                renderTodo('active')
              }}
              style={{
                color: tab === 'active' ? '#000' : '#aaa',
              }}
            >
              Active
            </a>
          </li>
          <li>
            <a
              href="javascript:;"
              onClick={(e) => {
                e.preventDefault()
                setTab('completed')
                renderTodo('completed')
              }}
              style={{
                color: tab === 'completed' ? '#000' : '#aaa',
              }}
            >
              Completed
            </a>
          </li>
        </ul>
      </div>
      <h2>{tab.charAt(0).toUpperCase() + tab.slice(1)} todos</h2>
      {todos.length < 1 && (
        <div className="no-todo-container">
          <em>Oops, no {tab !== 'all' && tab} todo. Add one!</em>
        </div>
      )}
      <ul
        className="todo-list"
        style={{
          padding: 0,
          display: 'flex',
          flexWrap: 'wrap',
          gap: '1rem',
        }}
      >
        {todos.map((item, index) => (
          <TodoCard key={index} index={index} item={item} />
        ))}
      </ul>
      {todos.length > 0 && (
        <div className="clear-todo-container">
          <a
            href="javascript:;"
            onClick={(e) => {
              e.preventDefault()
              globalStore.dispatch({
                type: 'clearTodos',
              })
            }}
          >
            Delete all todos
          </a>
        </div>
      )}
    </div>
  )
}

export default connect()(TodoList)
