// projects/react/src/components/TodoCard.tsx
import { connect } from 'react-redux'
import { Todo } from '../types/Todo'
import { Icon } from '@ricons/utils'
import { Trash, Pen, CheckCircle, CircleRegular } from '@ricons/fa'

const TodoCard = (payload: { index: number; item: Todo; dispatch: any }) => {
  const { index, item, dispatch } = payload
  return (
    <li
      key={index}
      className="todo-card"
      style={{
        listStyle: 'none',
        width: '100%',
        padding: '1rem',
        backgroundColor: '#fff',
        color: '#000',
        boxShadow: `0 0 0.5rem 0.5rem #eee`,
        borderRadius: '0.5rem',
        display: 'flex',
        gap: '1rem',
        // flexDirection: 'column',
        alignItems: 'center',
      }}
    >
      <div className="todo-check-area" style={{}}>
        <a
          onClick={(e) => {
            dispatch({
              type: 'updateTodo',
              payload: {
                uuid: item.uuid,
                completedAt: !!item.completedAt ? '' : new Date().toISOString(),
              },
            })
          }}
          style={{
            cursor: 'pointer',
            color: !!item.completedAt ? '#0066cc' : '#ccc',
            fontSize: '2rem',
          }}
        >
          {!!item.completedAt ? (
            <Icon>
              <CheckCircle></CheckCircle>
            </Icon>
          ) : (
            <Icon>
              <CircleRegular></CircleRegular>
            </Icon>
          )}
        </a>
      </div>
      <div
        className="todo-main-area"
        style={{
          flex: 1,
        }}
      >
        <div
          className="todo-title"
          style={{
            fontWeight: 'bold',
            fontSize: '1.25rem',
            textDecoration: !!item.completedAt ? 'line-through' : 'none',
            color: !!item.completedAt ? '#aaa' : '#000',
          }}
        >
          {item.title || 'No title'}
          {/* {!!item.completedAt && (
            <>
              {' '}
              <Icon color="green">
                <Check></Check>
              </Icon>
            </>
          )} */}
        </div>
        <div
          className="todo-content"
          style={{
            textDecoration: !!item.completedAt ? 'line-through' : 'none',
            margin: '1rem 0',
            color: !!item.completedAt ? '#aaa' : '#000',
          }}
        >
          {item.content}
        </div>
        <div
          className="todo-time"
          style={{
            fontSize: '0.8rem',
            fontStyle: 'italic',
            color: '#aaa',
          }}
        >
          <em className="todo-time-created">
            Created at: {new Date(item.createdAt).toLocaleString()}
          </em>
          {item.completedAt && (
            <>
              {' | '}
              <em className="todo-time-completed">
                Completed at: {new Date(item.completedAt).toLocaleString()}
              </em>
            </>
          )}
        </div>
        <div
          className="todo-actions"
          style={{
            display: 'flex',
            width: '100%',
            gap: '1em',
            marginTop: '1rem',
          }}
        >
          <a>
            <Icon>
              <Pen></Pen>
            </Icon>
          </a>
          <a
            onClick={(e) => {
              dispatch({
                type: 'removeTodo',
                payload: item.uuid,
              })
            }}
            style={{
              cursor: 'pointer',
            }}
          >
            <Icon color="darkred">
              <Trash />
            </Icon>
          </a>
        </div>
      </div>
    </li>
  )
}

export default connect()(TodoCard)

// projects/vue3/src/components/TodoCard.vue
<template lang="pug">
li.todo-card(:class="!!todo.completedAt ? 'complated': 'active'")
  .todo-check
    a.todo-check-btn(@click="updateTodo({ ...todo, completedAt: !!todo.completedAt ? '' : new Date().toISOString()})")
      icon
        check-circle(v-if="!!todo.completedAt")
        circle-regular(v-else)
  .todo-main
    .todo-title {{ todo.title }}
    .todo-content {{ todo.content }}
    .todo-time
      em.todo-time-created Created at: {{ new Date(todo.createdAt).toLocaleString() }}
      | {{ !!todo.completedAt ? '&nbsp;|&nbsp;' : '' }}
      em.todo-time-complated(v-if="!!todo.completedAt") Complated at: {{ new Date(todo.completedAt).toLocaleString() }}
    .todo-actions
      a.edit-btn
        icon
          pen
      a.delete-btn(@click="removeTodo(todo.uuid)")
        icon(color="darkred")
          trash
</template>

<script setup lang="ts">
import {} from 'vue'
import { CheckCircle, CircleRegular, Pen, Trash } from '@vicons/fa'
import { updateTodo, removeTodo } from '../utils/globalState'
import type { Todo } from '../types/Todo'
const props = defineProps<{
  todo: Todo
}>()
</script>

<style scoped lang="sass">
.todo-card
  list-style: none
  width: 100%
  background-color: #fff
  padding: 1rem
  border-radius: 0.5rem
  box-shadow: 0 0 0.5rem rgba(0, 0, 0, 0.1)
  display: flex
  gap: 1rem
  align-items: center

  .todo-main
    flex: 1

    .todo-title
      font-size: 1.25rem
      font-weight: bold
      margin: 0 0 1rem 0
    .todo-content
      // font-size: 1.2rem
      margin: 0 0 1rem 0
    .todo-time
      font-size: 0.8rem
      color: #ccc
    .todo-actions
      margin-top: 1rem
      display: flex
      gap: 1rem
      a
        cursor: pointer

  .todo-check
    a
      cursor: pointer
      font-size: 2rem
      display: block
      color: #ccc

  &.active
    .todo-check
      a:hover
        color: #aaa

  &.complated
    .todo-main
      .todo-title, .todo-content
        text-decoration: line-through
        color: #aaa
    .todo-check
      a
        color: green
</style>
